spring.application.name=refreshtokenarchitecture

# embedded H2 database for demo purposes
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# 512 bit secret-key
security.jwt.secret-key=VAhFzFinEQoCQdkqcDVqb05hknw7G5kCL3cjGYMC4FCRdwvu2VjKG7ns5KFcgyGKWd2DKP1OhKLNwxqOZAxhaX
# 15 minutes in seconds
security.jwt.access-expiration-time=900
# 30 days in seconds
security.jwt.refresh-expiration-time=2592000

server.port=8080